[package]
name = "contract"
version = "0.1.0"
edition = "2018"

[dependencies]
casper-contract = { version = "1.4.4", features = ["test-support"] }
casper-types = "1.5.0"

[[bin]]
name = "contract"
path = "src/main.rs"
bench = false
doctest = false
test = false
